name: POSIX Script Version Tests

on:
  pull_request:

jobs:
  setup-lando-os-test:
    runs-on: ${{ matrix.os }}
    env:
      term: xterm
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        success-version:
          - '3.x'
          - '>2'
          - '3'
          - '3.14'
          - '3.14.0'
          - 'v3.21.0-alpha.9-slim'
          - '3-slim'
          - '3-stable'
          - '3-stable-slim'
          - '3-edge'
          - '3-edge-slim'
          - '3-latest'
          - '3-dev'
          - '3-dev-slim'
          - 'stable'
          - 'edge'
          - 'latest'
          - 'dev'
          - 'pm-preview'
          - 'https://github.com/lando/cli/releases/download/v3.18.0/lando-linux-x64-v3.18.0'
          - '/home/runner/work/setup-lando/setup-lando/bin/lando'
          - './bin/lando'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Lando version ${{ matrix.success-version }}
        shell: bash
        run: ./setup-lando.sh --version=${{ matrix.success-version }} --no-setup
      - name: Verify Lando is in PATH
        shell: bash
        run: lando version
