name: POSIX Script Version Tests

on:
  pull_request:

jobs:
  setup-lando-os-test:
    runs-on: ${{ matrix.os }}
    env:
      term: xterm
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        success-version:
          - '3'
          - 'v3.21.0-alpha.9'
          - '3-stable'
          - '3-edge'
          - '3-edge'
          - '3-latest'
          - '3-dev'
          - 'stable'
          - 'edge'
          - 'latest'
          - 'dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Lando version ${{ matrix.success-version }}
        shell: bash
        run: |
          ./setup-lando.sh --version=${{ matrix.success-version }} --no-setup
          lando version
