name: Windows Script Pipeline Tests

on:
  pull_request:

jobs:
  setup-lando-windows-pipeline-test:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        shell:
          - powershell
          - pwsh

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - if: matrix.shell == 'powershell'
        name: Invoke from pipeline with PowerShell 5.1
        shell: powershell
        run: |
          Invoke-WebRequest "file://${{ github.workspace }}/setup-lando.ps1" | Invoke-Expression
          Test-Path $env:LOCALAPPDATA\Lando\setup-lando.ps1
          lando version --all
      
      - if: matrix.shell == 'pwsh'
        name: Invoke from pipeline with PowerShell 7
        shell: pwsh
        run: |
          Get-Content "${{ github.workspace }}/setup-lando.ps1" -Raw | Invoke-Expression
          Test-Path $env:LOCALAPPDATA\Lando\setup-lando.ps1
          lando version --all
      

